const SocketEventName = {
    updateUser: 'update-user',
    join: 'john',
    getOnlineUsers: 'get-online-users',
    leave: 'leave',
    sendMessage: 'send-message',
    sendMessageByConversationId: 'send-message-by-conversation-id',
    typing: 'typing',
    stopTyping: 'stop-typing',
    receiveMessage: 'receive-message',
    onlineUsers: 'online-users',
    newJoiner: 'new-joiner',
    userLeaveRoom: 'user-leave-room',
    userLeft: 'user-left',
    acceptFriend: 'accept-friend',
    addFriend: 'add-friend',
    unfriend: 'unfriend',
    cancelFriendRequest: 'cancel-friend-request',
    deleteFriendRequest: 'delete-friend-request',
    friendRequestCanceled: 'friend-request-canceled',
    friendRejected: 'friend-rejected',
    friendAccepted: 'friend-accepted',
    friendRequested: 'friend-requested',
    friendUnfriend: 'friend-unfriend',
}
export default SocketEventName;